// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.2
// source: app/order/cmd/rpc/pb/order.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderClient interface {
	//机票下订单
	CreateFlightOrder(ctx context.Context, in *CreateFlightOrderReq, opts ...grpc.CallOption) (*CreateFlightOrderResp, error)
	//机票订单详情
	FlightOrderDetail(ctx context.Context, in *FlightOrderDetailReq, opts ...grpc.CallOption) (*FlightOrderDetailResp, error)
	//更新机票订单状态
	UpdateFlightOrderTradeState(ctx context.Context, in *UpdateFlightOrderTradeStateReq, opts ...grpc.CallOption) (*UpdateFlightOrderTradeStateResp, error)
	//用户机票订单
	UserFlightOrderList(ctx context.Context, in *UserFlightOrderListReq, opts ...grpc.CallOption) (*UserFlightOrderListResp, error)
}

type orderClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderClient(cc grpc.ClientConnInterface) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) CreateFlightOrder(ctx context.Context, in *CreateFlightOrderReq, opts ...grpc.CallOption) (*CreateFlightOrderResp, error) {
	out := new(CreateFlightOrderResp)
	err := c.cc.Invoke(ctx, "/pb.order/CreateFlightOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) FlightOrderDetail(ctx context.Context, in *FlightOrderDetailReq, opts ...grpc.CallOption) (*FlightOrderDetailResp, error) {
	out := new(FlightOrderDetailResp)
	err := c.cc.Invoke(ctx, "/pb.order/FlightOrderDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) UpdateFlightOrderTradeState(ctx context.Context, in *UpdateFlightOrderTradeStateReq, opts ...grpc.CallOption) (*UpdateFlightOrderTradeStateResp, error) {
	out := new(UpdateFlightOrderTradeStateResp)
	err := c.cc.Invoke(ctx, "/pb.order/UpdateFlightOrderTradeState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) UserFlightOrderList(ctx context.Context, in *UserFlightOrderListReq, opts ...grpc.CallOption) (*UserFlightOrderListResp, error) {
	out := new(UserFlightOrderListResp)
	err := c.cc.Invoke(ctx, "/pb.order/UserFlightOrderList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
// All implementations must embed UnimplementedOrderServer
// for forward compatibility
type OrderServer interface {
	//机票下订单
	CreateFlightOrder(context.Context, *CreateFlightOrderReq) (*CreateFlightOrderResp, error)
	//机票订单详情
	FlightOrderDetail(context.Context, *FlightOrderDetailReq) (*FlightOrderDetailResp, error)
	//更新机票订单状态
	UpdateFlightOrderTradeState(context.Context, *UpdateFlightOrderTradeStateReq) (*UpdateFlightOrderTradeStateResp, error)
	//用户机票订单
	UserFlightOrderList(context.Context, *UserFlightOrderListReq) (*UserFlightOrderListResp, error)
	mustEmbedUnimplementedOrderServer()
}

// UnimplementedOrderServer must be embedded to have forward compatible implementations.
type UnimplementedOrderServer struct {
}

func (UnimplementedOrderServer) CreateFlightOrder(context.Context, *CreateFlightOrderReq) (*CreateFlightOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFlightOrder not implemented")
}
func (UnimplementedOrderServer) FlightOrderDetail(context.Context, *FlightOrderDetailReq) (*FlightOrderDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlightOrderDetail not implemented")
}
func (UnimplementedOrderServer) UpdateFlightOrderTradeState(context.Context, *UpdateFlightOrderTradeStateReq) (*UpdateFlightOrderTradeStateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFlightOrderTradeState not implemented")
}
func (UnimplementedOrderServer) UserFlightOrderList(context.Context, *UserFlightOrderListReq) (*UserFlightOrderListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserFlightOrderList not implemented")
}
func (UnimplementedOrderServer) mustEmbedUnimplementedOrderServer() {}

// UnsafeOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServer will
// result in compilation errors.
type UnsafeOrderServer interface {
	mustEmbedUnimplementedOrderServer()
}

func RegisterOrderServer(s grpc.ServiceRegistrar, srv OrderServer) {
	s.RegisterService(&Order_ServiceDesc, srv)
}

func _Order_CreateFlightOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFlightOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateFlightOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.order/CreateFlightOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateFlightOrder(ctx, req.(*CreateFlightOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_FlightOrderDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightOrderDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).FlightOrderDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.order/FlightOrderDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).FlightOrderDetail(ctx, req.(*FlightOrderDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_UpdateFlightOrderTradeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFlightOrderTradeStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).UpdateFlightOrderTradeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.order/UpdateFlightOrderTradeState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).UpdateFlightOrderTradeState(ctx, req.(*UpdateFlightOrderTradeStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_UserFlightOrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFlightOrderListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).UserFlightOrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.order/UserFlightOrderList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).UserFlightOrderList(ctx, req.(*UserFlightOrderListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Order_ServiceDesc is the grpc.ServiceDesc for Order service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Order_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFlightOrder",
			Handler:    _Order_CreateFlightOrder_Handler,
		},
		{
			MethodName: "FlightOrderDetail",
			Handler:    _Order_FlightOrderDetail_Handler,
		},
		{
			MethodName: "UpdateFlightOrderTradeState",
			Handler:    _Order_UpdateFlightOrderTradeState_Handler,
		},
		{
			MethodName: "UserFlightOrderList",
			Handler:    _Order_UserFlightOrderList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/order/cmd/rpc/pb/order.proto",
}
