// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.2
// source: app/mqueue/cmd/rpc/pb/mqueue.proto

//消息队列

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AqDeferFlightOrderCloseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sn string `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn"`
}

func (x *AqDeferFlightOrderCloseReq) Reset() {
	*x = AqDeferFlightOrderCloseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AqDeferFlightOrderCloseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AqDeferFlightOrderCloseReq) ProtoMessage() {}

func (x *AqDeferFlightOrderCloseReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AqDeferFlightOrderCloseReq.ProtoReflect.Descriptor instead.
func (*AqDeferFlightOrderCloseReq) Descriptor() ([]byte, []int) {
	return file_app_mqueue_cmd_rpc_pb_mqueue_proto_rawDescGZIP(), []int{0}
}

func (x *AqDeferFlightOrderCloseReq) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

type AqDeferFlightOrderCloseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AqDeferFlightOrderCloseResp) Reset() {
	*x = AqDeferFlightOrderCloseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AqDeferFlightOrderCloseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AqDeferFlightOrderCloseResp) ProtoMessage() {}

func (x *AqDeferFlightOrderCloseResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AqDeferFlightOrderCloseResp.ProtoReflect.Descriptor instead.
func (*AqDeferFlightOrderCloseResp) Descriptor() ([]byte, []int) {
	return file_app_mqueue_cmd_rpc_pb_mqueue_proto_rawDescGZIP(), []int{1}
}

type KqPaymentStatusUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderSn   string `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn"`
	PayStatus int64  `protobuf:"varint,2,opt,name=payStatus,proto3" json:"payStatus"`
}

func (x *KqPaymentStatusUpdateReq) Reset() {
	*x = KqPaymentStatusUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KqPaymentStatusUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KqPaymentStatusUpdateReq) ProtoMessage() {}

func (x *KqPaymentStatusUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KqPaymentStatusUpdateReq.ProtoReflect.Descriptor instead.
func (*KqPaymentStatusUpdateReq) Descriptor() ([]byte, []int) {
	return file_app_mqueue_cmd_rpc_pb_mqueue_proto_rawDescGZIP(), []int{2}
}

func (x *KqPaymentStatusUpdateReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *KqPaymentStatusUpdateReq) GetPayStatus() int64 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

type KqPaymentStatusUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KqPaymentStatusUpdateResp) Reset() {
	*x = KqPaymentStatusUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KqPaymentStatusUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KqPaymentStatusUpdateResp) ProtoMessage() {}

func (x *KqPaymentStatusUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KqPaymentStatusUpdateResp.ProtoReflect.Descriptor instead.
func (*KqPaymentStatusUpdateResp) Descriptor() ([]byte, []int) {
	return file_app_mqueue_cmd_rpc_pb_mqueue_proto_rawDescGZIP(), []int{3}
}

type SendWxMiniSubMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Openid     string            `protobuf:"bytes,1,opt,name=Openid,proto3" json:"Openid"`
	TemplateID string            `protobuf:"bytes,2,opt,name=TemplateID,proto3" json:"TemplateID"`
	Page       string            `protobuf:"bytes,3,opt,name=Page,proto3" json:"Page"`
	Data       map[string]string `protobuf:"bytes,4,rep,name=Data,proto3" json:"Data" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SendWxMiniSubMessageReq) Reset() {
	*x = SendWxMiniSubMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendWxMiniSubMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWxMiniSubMessageReq) ProtoMessage() {}

func (x *SendWxMiniSubMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWxMiniSubMessageReq.ProtoReflect.Descriptor instead.
func (*SendWxMiniSubMessageReq) Descriptor() ([]byte, []int) {
	return file_app_mqueue_cmd_rpc_pb_mqueue_proto_rawDescGZIP(), []int{4}
}

func (x *SendWxMiniSubMessageReq) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *SendWxMiniSubMessageReq) GetTemplateID() string {
	if x != nil {
		return x.TemplateID
	}
	return ""
}

func (x *SendWxMiniSubMessageReq) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *SendWxMiniSubMessageReq) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendWxMiniSubMessageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendWxMiniSubMessageResp) Reset() {
	*x = SendWxMiniSubMessageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendWxMiniSubMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWxMiniSubMessageResp) ProtoMessage() {}

func (x *SendWxMiniSubMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWxMiniSubMessageResp.ProtoReflect.Descriptor instead.
func (*SendWxMiniSubMessageResp) Descriptor() ([]byte, []int) {
	return file_app_mqueue_cmd_rpc_pb_mqueue_proto_rawDescGZIP(), []int{5}
}

var File_app_mqueue_cmd_rpc_pb_mqueue_proto protoreflect.FileDescriptor

var file_app_mqueue_cmd_rpc_pb_mqueue_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x70, 0x70, 0x2f, 0x6d, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2f, 0x63, 0x6d, 0x64,
	0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2c, 0x0a, 0x1a, 0x41, 0x71, 0x44, 0x65,
	0x66, 0x65, 0x72, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x73, 0x6e, 0x22, 0x1d, 0x0a, 0x1b, 0x41, 0x71, 0x44, 0x65, 0x66, 0x65,
	0x72, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x52, 0x0a, 0x18, 0x4b, 0x71, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x70, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1b, 0x0a, 0x19, 0x4b, 0x71, 0x50,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0xd9, 0x01, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x57,
	0x78, 0x4d, 0x69, 0x6e, 0x69, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x39,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x78, 0x4d, 0x69, 0x6e, 0x69, 0x53, 0x75, 0x62, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x61, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x1a, 0x0a, 0x18, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x78, 0x4d, 0x69, 0x6e, 0x69,
	0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x32, 0x8d,
	0x02, 0x0a, 0x06, 0x6d, 0x71, 0x75, 0x65, 0x75, 0x65, 0x12, 0x5a, 0x0a, 0x17, 0x61, 0x71, 0x44,
	0x65, 0x66, 0x65, 0x72, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x12, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x71, 0x44, 0x65, 0x66, 0x65,
	0x72, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x71, 0x44, 0x65, 0x66, 0x65,
	0x72, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x54, 0x0a, 0x15, 0x6b, 0x71, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1c,
	0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x71, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x70,
	0x62, 0x2e, 0x4b, 0x71, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x51, 0x0a, 0x14, 0x73,
	0x65, 0x6e, 0x64, 0x57, 0x78, 0x4d, 0x69, 0x6e, 0x69, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x78, 0x4d,
	0x69, 0x6e, 0x69, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x78, 0x4d, 0x69, 0x6e, 0x69,
	0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_mqueue_cmd_rpc_pb_mqueue_proto_rawDescOnce sync.Once
	file_app_mqueue_cmd_rpc_pb_mqueue_proto_rawDescData = file_app_mqueue_cmd_rpc_pb_mqueue_proto_rawDesc
)

func file_app_mqueue_cmd_rpc_pb_mqueue_proto_rawDescGZIP() []byte {
	file_app_mqueue_cmd_rpc_pb_mqueue_proto_rawDescOnce.Do(func() {
		file_app_mqueue_cmd_rpc_pb_mqueue_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_mqueue_cmd_rpc_pb_mqueue_proto_rawDescData)
	})
	return file_app_mqueue_cmd_rpc_pb_mqueue_proto_rawDescData
}

var file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_app_mqueue_cmd_rpc_pb_mqueue_proto_goTypes = []interface{}{
	(*AqDeferFlightOrderCloseReq)(nil),  // 0: pb.AqDeferFlightOrderCloseReq
	(*AqDeferFlightOrderCloseResp)(nil), // 1: pb.AqDeferFlightOrderCloseResp
	(*KqPaymentStatusUpdateReq)(nil),    // 2: pb.KqPaymentStatusUpdateReq
	(*KqPaymentStatusUpdateResp)(nil),   // 3: pb.KqPaymentStatusUpdateResp
	(*SendWxMiniSubMessageReq)(nil),     // 4: pb.SendWxMiniSubMessageReq
	(*SendWxMiniSubMessageResp)(nil),    // 5: pb.SendWxMiniSubMessageResp
	nil,                                 // 6: pb.SendWxMiniSubMessageReq.DataEntry
}
var file_app_mqueue_cmd_rpc_pb_mqueue_proto_depIdxs = []int32{
	6, // 0: pb.SendWxMiniSubMessageReq.Data:type_name -> pb.SendWxMiniSubMessageReq.DataEntry
	0, // 1: pb.mqueue.aqDeferFlightOrderClose:input_type -> pb.AqDeferFlightOrderCloseReq
	2, // 2: pb.mqueue.kqPaymentStatusUpdate:input_type -> pb.KqPaymentStatusUpdateReq
	4, // 3: pb.mqueue.sendWxMiniSubMessage:input_type -> pb.SendWxMiniSubMessageReq
	1, // 4: pb.mqueue.aqDeferFlightOrderClose:output_type -> pb.AqDeferFlightOrderCloseResp
	3, // 5: pb.mqueue.kqPaymentStatusUpdate:output_type -> pb.KqPaymentStatusUpdateResp
	5, // 6: pb.mqueue.sendWxMiniSubMessage:output_type -> pb.SendWxMiniSubMessageResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_mqueue_cmd_rpc_pb_mqueue_proto_init() }
func file_app_mqueue_cmd_rpc_pb_mqueue_proto_init() {
	if File_app_mqueue_cmd_rpc_pb_mqueue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AqDeferFlightOrderCloseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AqDeferFlightOrderCloseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KqPaymentStatusUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KqPaymentStatusUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendWxMiniSubMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendWxMiniSubMessageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_mqueue_cmd_rpc_pb_mqueue_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_mqueue_cmd_rpc_pb_mqueue_proto_goTypes,
		DependencyIndexes: file_app_mqueue_cmd_rpc_pb_mqueue_proto_depIdxs,
		MessageInfos:      file_app_mqueue_cmd_rpc_pb_mqueue_proto_msgTypes,
	}.Build()
	File_app_mqueue_cmd_rpc_pb_mqueue_proto = out.File
	file_app_mqueue_cmd_rpc_pb_mqueue_proto_rawDesc = nil
	file_app_mqueue_cmd_rpc_pb_mqueue_proto_goTypes = nil
	file_app_mqueue_cmd_rpc_pb_mqueue_proto_depIdxs = nil
}
