// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.2
// source: app/mqueue/cmd/rpc/pb/mqueue.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MqueueClient is the client API for Mqueue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MqueueClient interface {
	//添加航班订单延迟关闭到asynq队列
	AqDeferFlightOrderClose(ctx context.Context, in *AqDeferFlightOrderCloseReq, opts ...grpc.CallOption) (*AqDeferFlightOrderCloseResp, error)
	//支付流水状态变更发送到kq
	KqPaymentStatusUpdate(ctx context.Context, in *KqPaymentStatusUpdateReq, opts ...grpc.CallOption) (*KqPaymentStatusUpdateResp, error)
	//发送微信小程序订阅消息
	SendWxMiniSubMessage(ctx context.Context, in *SendWxMiniSubMessageReq, opts ...grpc.CallOption) (*SendWxMiniSubMessageResp, error)
}

type mqueueClient struct {
	cc grpc.ClientConnInterface
}

func NewMqueueClient(cc grpc.ClientConnInterface) MqueueClient {
	return &mqueueClient{cc}
}

func (c *mqueueClient) AqDeferFlightOrderClose(ctx context.Context, in *AqDeferFlightOrderCloseReq, opts ...grpc.CallOption) (*AqDeferFlightOrderCloseResp, error) {
	out := new(AqDeferFlightOrderCloseResp)
	err := c.cc.Invoke(ctx, "/pb.mqueue/aqDeferFlightOrderClose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqueueClient) KqPaymentStatusUpdate(ctx context.Context, in *KqPaymentStatusUpdateReq, opts ...grpc.CallOption) (*KqPaymentStatusUpdateResp, error) {
	out := new(KqPaymentStatusUpdateResp)
	err := c.cc.Invoke(ctx, "/pb.mqueue/kqPaymentStatusUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqueueClient) SendWxMiniSubMessage(ctx context.Context, in *SendWxMiniSubMessageReq, opts ...grpc.CallOption) (*SendWxMiniSubMessageResp, error) {
	out := new(SendWxMiniSubMessageResp)
	err := c.cc.Invoke(ctx, "/pb.mqueue/sendWxMiniSubMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MqueueServer is the server API for Mqueue service.
// All implementations must embed UnimplementedMqueueServer
// for forward compatibility
type MqueueServer interface {
	//添加航班订单延迟关闭到asynq队列
	AqDeferFlightOrderClose(context.Context, *AqDeferFlightOrderCloseReq) (*AqDeferFlightOrderCloseResp, error)
	//支付流水状态变更发送到kq
	KqPaymentStatusUpdate(context.Context, *KqPaymentStatusUpdateReq) (*KqPaymentStatusUpdateResp, error)
	//发送微信小程序订阅消息
	SendWxMiniSubMessage(context.Context, *SendWxMiniSubMessageReq) (*SendWxMiniSubMessageResp, error)
	mustEmbedUnimplementedMqueueServer()
}

// UnimplementedMqueueServer must be embedded to have forward compatible implementations.
type UnimplementedMqueueServer struct {
}

func (UnimplementedMqueueServer) AqDeferFlightOrderClose(context.Context, *AqDeferFlightOrderCloseReq) (*AqDeferFlightOrderCloseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AqDeferFlightOrderClose not implemented")
}
func (UnimplementedMqueueServer) KqPaymentStatusUpdate(context.Context, *KqPaymentStatusUpdateReq) (*KqPaymentStatusUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KqPaymentStatusUpdate not implemented")
}
func (UnimplementedMqueueServer) SendWxMiniSubMessage(context.Context, *SendWxMiniSubMessageReq) (*SendWxMiniSubMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWxMiniSubMessage not implemented")
}
func (UnimplementedMqueueServer) mustEmbedUnimplementedMqueueServer() {}

// UnsafeMqueueServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MqueueServer will
// result in compilation errors.
type UnsafeMqueueServer interface {
	mustEmbedUnimplementedMqueueServer()
}

func RegisterMqueueServer(s grpc.ServiceRegistrar, srv MqueueServer) {
	s.RegisterService(&Mqueue_ServiceDesc, srv)
}

func _Mqueue_AqDeferFlightOrderClose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AqDeferFlightOrderCloseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqueueServer).AqDeferFlightOrderClose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.mqueue/aqDeferFlightOrderClose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqueueServer).AqDeferFlightOrderClose(ctx, req.(*AqDeferFlightOrderCloseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mqueue_KqPaymentStatusUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KqPaymentStatusUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqueueServer).KqPaymentStatusUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.mqueue/kqPaymentStatusUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqueueServer).KqPaymentStatusUpdate(ctx, req.(*KqPaymentStatusUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mqueue_SendWxMiniSubMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWxMiniSubMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqueueServer).SendWxMiniSubMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.mqueue/sendWxMiniSubMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqueueServer).SendWxMiniSubMessage(ctx, req.(*SendWxMiniSubMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Mqueue_ServiceDesc is the grpc.ServiceDesc for Mqueue service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mqueue_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.mqueue",
	HandlerType: (*MqueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "aqDeferFlightOrderClose",
			Handler:    _Mqueue_AqDeferFlightOrderClose_Handler,
		},
		{
			MethodName: "kqPaymentStatusUpdate",
			Handler:    _Mqueue_KqPaymentStatusUpdate_Handler,
		},
		{
			MethodName: "sendWxMiniSubMessage",
			Handler:    _Mqueue_SendWxMiniSubMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/mqueue/cmd/rpc/pb/mqueue.proto",
}
