// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: app/stock/cmd/rpc/pb/stock.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 加库存
type AddStockByTicketIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketID int64 `protobuf:"varint,1,opt,name=ticketID,proto3" json:"ticketID,omitempty"`
	Num      int64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *AddStockByTicketIDReq) Reset() {
	*x = AddStockByTicketIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStockByTicketIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStockByTicketIDReq) ProtoMessage() {}

func (x *AddStockByTicketIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStockByTicketIDReq.ProtoReflect.Descriptor instead.
func (*AddStockByTicketIDReq) Descriptor() ([]byte, []int) {
	return file_app_stock_cmd_rpc_pb_stock_proto_rawDescGZIP(), []int{0}
}

func (x *AddStockByTicketIDReq) GetTicketID() int64 {
	if x != nil {
		return x.TicketID
	}
	return 0
}

func (x *AddStockByTicketIDReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type AddStockBySpaceIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceID int64 `protobuf:"varint,1,opt,name=spaceID,proto3" json:"spaceID,omitempty"`
	Num     int64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *AddStockBySpaceIDReq) Reset() {
	*x = AddStockBySpaceIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStockBySpaceIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStockBySpaceIDReq) ProtoMessage() {}

func (x *AddStockBySpaceIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStockBySpaceIDReq.ProtoReflect.Descriptor instead.
func (*AddStockBySpaceIDReq) Descriptor() ([]byte, []int) {
	return file_app_stock_cmd_rpc_pb_stock_proto_rawDescGZIP(), []int{1}
}

func (x *AddStockBySpaceIDReq) GetSpaceID() int64 {
	if x != nil {
		return x.SpaceID
	}
	return 0
}

func (x *AddStockBySpaceIDReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type AddStockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddStockResp) Reset() {
	*x = AddStockResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStockResp) ProtoMessage() {}

func (x *AddStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStockResp.ProtoReflect.Descriptor instead.
func (*AddStockResp) Descriptor() ([]byte, []int) {
	return file_app_stock_cmd_rpc_pb_stock_proto_rawDescGZIP(), []int{2}
}

// 扣库存
type DeductStockByTicketIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketID int64 `protobuf:"varint,1,opt,name=ticketID,proto3" json:"ticketID,omitempty"`
	Num      int64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *DeductStockByTicketIDReq) Reset() {
	*x = DeductStockByTicketIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeductStockByTicketIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockByTicketIDReq) ProtoMessage() {}

func (x *DeductStockByTicketIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockByTicketIDReq.ProtoReflect.Descriptor instead.
func (*DeductStockByTicketIDReq) Descriptor() ([]byte, []int) {
	return file_app_stock_cmd_rpc_pb_stock_proto_rawDescGZIP(), []int{3}
}

func (x *DeductStockByTicketIDReq) GetTicketID() int64 {
	if x != nil {
		return x.TicketID
	}
	return 0
}

func (x *DeductStockByTicketIDReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type DeductStockBySpaceIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceID int64 `protobuf:"varint,1,opt,name=spaceID,proto3" json:"spaceID,omitempty"`
	Num     int64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *DeductStockBySpaceIDReq) Reset() {
	*x = DeductStockBySpaceIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeductStockBySpaceIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockBySpaceIDReq) ProtoMessage() {}

func (x *DeductStockBySpaceIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockBySpaceIDReq.ProtoReflect.Descriptor instead.
func (*DeductStockBySpaceIDReq) Descriptor() ([]byte, []int) {
	return file_app_stock_cmd_rpc_pb_stock_proto_rawDescGZIP(), []int{4}
}

func (x *DeductStockBySpaceIDReq) GetSpaceID() int64 {
	if x != nil {
		return x.SpaceID
	}
	return 0
}

func (x *DeductStockBySpaceIDReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type DeductStockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeductStockResp) Reset() {
	*x = DeductStockResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeductStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockResp) ProtoMessage() {}

func (x *DeductStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockResp.ProtoReflect.Descriptor instead.
func (*DeductStockResp) Descriptor() ([]byte, []int) {
	return file_app_stock_cmd_rpc_pb_stock_proto_rawDescGZIP(), []int{5}
}

var File_app_stock_cmd_rpc_pb_stock_proto protoreflect.FileDescriptor

var file_app_stock_cmd_rpc_pb_stock_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x70, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2f, 0x63, 0x6d, 0x64, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x45, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x42, 0x79, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x6e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x42, 0x0a,
	0x14, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x42, 0x79, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12,
	0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75,
	0x6d, 0x22, 0x0e, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x48, 0x0a, 0x18, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x42, 0x79, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x45, 0x0a, 0x17, 0x44,
	0x65, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x42, 0x79, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e,
	0x75, 0x6d, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x32, 0xdb, 0x04, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12,
	0x41, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x42, 0x79, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x49, 0x44, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x42, 0x79, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x49, 0x0a, 0x1a, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x42, 0x79,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x52, 0x6f, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b,
	0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x42, 0x79,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x62,
	0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a,
	0x11, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x42, 0x79, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x49, 0x44, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x42, 0x79, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x47,
	0x0a, 0x19, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x42, 0x79, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x49, 0x44, 0x52, 0x6f, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x12, 0x18, 0x2e, 0x70, 0x62,
	0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x42, 0x79, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4a, 0x0a, 0x15, 0x44, 0x65, 0x64, 0x75, 0x63,
	0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x42, 0x79, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44,
	0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x63,
	0x6b, 0x42, 0x79, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x52, 0x0a, 0x1d, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x42, 0x79, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x52, 0x6f, 0x6c, 0x6c,
	0x42, 0x61, 0x63, 0x6b, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x42, 0x79, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x48, 0x0a, 0x14, 0x44, 0x65, 0x64, 0x75, 0x63,
	0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x42, 0x79, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12,
	0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x42, 0x79, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x50, 0x0a, 0x1c, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x42, 0x79, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x52, 0x6f, 0x6c, 0x6c, 0x42, 0x61, 0x63,
	0x6b, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x42, 0x79, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_app_stock_cmd_rpc_pb_stock_proto_rawDescOnce sync.Once
	file_app_stock_cmd_rpc_pb_stock_proto_rawDescData = file_app_stock_cmd_rpc_pb_stock_proto_rawDesc
)

func file_app_stock_cmd_rpc_pb_stock_proto_rawDescGZIP() []byte {
	file_app_stock_cmd_rpc_pb_stock_proto_rawDescOnce.Do(func() {
		file_app_stock_cmd_rpc_pb_stock_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_stock_cmd_rpc_pb_stock_proto_rawDescData)
	})
	return file_app_stock_cmd_rpc_pb_stock_proto_rawDescData
}

var file_app_stock_cmd_rpc_pb_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_app_stock_cmd_rpc_pb_stock_proto_goTypes = []interface{}{
	(*AddStockByTicketIDReq)(nil),    // 0: pb.AddStockByTicketIDReq
	(*AddStockBySpaceIDReq)(nil),     // 1: pb.AddStockBySpaceIDReq
	(*AddStockResp)(nil),             // 2: pb.AddStockResp
	(*DeductStockByTicketIDReq)(nil), // 3: pb.DeductStockByTicketIDReq
	(*DeductStockBySpaceIDReq)(nil),  // 4: pb.DeductStockBySpaceIDReq
	(*DeductStockResp)(nil),          // 5: pb.DeductStockResp
}
var file_app_stock_cmd_rpc_pb_stock_proto_depIdxs = []int32{
	0, // 0: pb.stock.AddStockByTicketID:input_type -> pb.AddStockByTicketIDReq
	0, // 1: pb.stock.AddStockByTicketIDRollBack:input_type -> pb.AddStockByTicketIDReq
	1, // 2: pb.stock.AddStockBySpaceID:input_type -> pb.AddStockBySpaceIDReq
	1, // 3: pb.stock.AddStockBySpaceIDRollBack:input_type -> pb.AddStockBySpaceIDReq
	3, // 4: pb.stock.DeductStockByTicketID:input_type -> pb.DeductStockByTicketIDReq
	3, // 5: pb.stock.DeductStockByTicketIDRollBack:input_type -> pb.DeductStockByTicketIDReq
	4, // 6: pb.stock.DeductStockBySpaceID:input_type -> pb.DeductStockBySpaceIDReq
	4, // 7: pb.stock.DeductStockBySpaceIDRollBack:input_type -> pb.DeductStockBySpaceIDReq
	2, // 8: pb.stock.AddStockByTicketID:output_type -> pb.AddStockResp
	2, // 9: pb.stock.AddStockByTicketIDRollBack:output_type -> pb.AddStockResp
	2, // 10: pb.stock.AddStockBySpaceID:output_type -> pb.AddStockResp
	2, // 11: pb.stock.AddStockBySpaceIDRollBack:output_type -> pb.AddStockResp
	5, // 12: pb.stock.DeductStockByTicketID:output_type -> pb.DeductStockResp
	5, // 13: pb.stock.DeductStockByTicketIDRollBack:output_type -> pb.DeductStockResp
	5, // 14: pb.stock.DeductStockBySpaceID:output_type -> pb.DeductStockResp
	5, // 15: pb.stock.DeductStockBySpaceIDRollBack:output_type -> pb.DeductStockResp
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_stock_cmd_rpc_pb_stock_proto_init() }
func file_app_stock_cmd_rpc_pb_stock_proto_init() {
	if File_app_stock_cmd_rpc_pb_stock_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStockByTicketIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStockBySpaceIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStockResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeductStockByTicketIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeductStockBySpaceIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_stock_cmd_rpc_pb_stock_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeductStockResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_stock_cmd_rpc_pb_stock_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_stock_cmd_rpc_pb_stock_proto_goTypes,
		DependencyIndexes: file_app_stock_cmd_rpc_pb_stock_proto_depIdxs,
		MessageInfos:      file_app_stock_cmd_rpc_pb_stock_proto_msgTypes,
	}.Build()
	File_app_stock_cmd_rpc_pb_stock_proto = out.File
	file_app_stock_cmd_rpc_pb_stock_proto_rawDesc = nil
	file_app_stock_cmd_rpc_pb_stock_proto_goTypes = nil
	file_app_stock_cmd_rpc_pb_stock_proto_depIdxs = nil
}
