// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	flightReservation "uranus/app/flightReservation/cmd/api/internal/handler/flightReservation"
	"uranus/app/flightReservation/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/reservation",
				Handler: flightReservation.FlightReservationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refund",
				Handler: flightReservation.FlightRefundHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/change",
				Handler: flightReservation.FlightChangeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/flightReservation/v1"),
	)
}
