// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	flightInquiry "uranus/app/flightInquiry/cmd/api/internal/handler/flightInquiry"
	"uranus/app/flightInquiry/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/quiry/date-number",
				Handler: flightInquiry.QuireBySetOutDateAndFlightNumberHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/quiry/date-position",
				Handler: flightInquiry.QuireBySetOutDateStartPositionEndPositionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/flightInquiry/v1"),
	)
}
