// Code generated by goctl. DO NOT EDIT!
// Source: mqueue.proto

package server

import (
	"context"

	"uranus/app/mqueue/cmd/rpc/internal/logic"
	"uranus/app/mqueue/cmd/rpc/internal/svc"
	"uranus/app/mqueue/cmd/rpc/pb"
)

type MqueueServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMqueueServer
}

func NewMqueueServer(svcCtx *svc.ServiceContext) *MqueueServer {
	return &MqueueServer{
		svcCtx: svcCtx,
	}
}

// 添加航班订单延迟关闭到asynq队列
func (s *MqueueServer) AqDeferFlightOrderClose(ctx context.Context, in *pb.AqDeferFlightOrderCloseReq) (*pb.AqDeferFlightOrderCloseResp, error) {
	l := logic.NewAqDeferFlightOrderCloseLogic(ctx, s.svcCtx)
	return l.AqDeferFlightOrderClose(in)
}

// 支付流水状态变更发送到kq
func (s *MqueueServer) KqPaymentStatusUpdate(ctx context.Context, in *pb.KqPaymentStatusUpdateReq) (*pb.KqPaymentStatusUpdateResp, error) {
	l := logic.NewKqPaymentStatusUpdateLogic(ctx, s.svcCtx)
	return l.KqPaymentStatusUpdate(in)
}

// 发送微信小程序订阅消息
func (s *MqueueServer) SendWxMiniSubMessage(ctx context.Context, in *pb.SendWxMiniSubMessageReq) (*pb.SendWxMiniSubMessageResp, error) {
	l := logic.NewSendWxMiniSubMessageLogic(ctx, s.svcCtx)
	return l.SendWxMiniSubMessage(in)
}
