// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.2
// source: app/flightInquiry/cmd/rpc/pb/flightInquiry.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FlightInquiryClient is the client API for FlightInquiry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlightInquiryClient interface {
	//QuireBySetOutDateAndFlightNumber 通过给定日期、航班号进行航班查询请求
	QuireBySetOutDateAndFlightNumber(ctx context.Context, in *QuireBySetOutDateAndFlightNumberReq, opts ...grpc.CallOption) (*QuireBySetOutDateAndFlightNumberResp, error)
	//QuireBySetOutDateStartPositionEndPosition 通过给定日期、出发地、目的地进行航班查询请求
	QuireBySetOutDateStartPositionEndPosition(ctx context.Context, in *QuireBySetOutDateStartPositionEndPositionReq, opts ...grpc.CallOption) (*QuireBySetOutDateStartPositionEndPositionResp, error)
}

type flightInquiryClient struct {
	cc grpc.ClientConnInterface
}

func NewFlightInquiryClient(cc grpc.ClientConnInterface) FlightInquiryClient {
	return &flightInquiryClient{cc}
}

func (c *flightInquiryClient) QuireBySetOutDateAndFlightNumber(ctx context.Context, in *QuireBySetOutDateAndFlightNumberReq, opts ...grpc.CallOption) (*QuireBySetOutDateAndFlightNumberResp, error) {
	out := new(QuireBySetOutDateAndFlightNumberResp)
	err := c.cc.Invoke(ctx, "/pb.flightInquiry/QuireBySetOutDateAndFlightNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightInquiryClient) QuireBySetOutDateStartPositionEndPosition(ctx context.Context, in *QuireBySetOutDateStartPositionEndPositionReq, opts ...grpc.CallOption) (*QuireBySetOutDateStartPositionEndPositionResp, error) {
	out := new(QuireBySetOutDateStartPositionEndPositionResp)
	err := c.cc.Invoke(ctx, "/pb.flightInquiry/QuireBySetOutDateStartPositionEndPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightInquiryServer is the server API for FlightInquiry service.
// All implementations must embed UnimplementedFlightInquiryServer
// for forward compatibility
type FlightInquiryServer interface {
	//QuireBySetOutDateAndFlightNumber 通过给定日期、航班号进行航班查询请求
	QuireBySetOutDateAndFlightNumber(context.Context, *QuireBySetOutDateAndFlightNumberReq) (*QuireBySetOutDateAndFlightNumberResp, error)
	//QuireBySetOutDateStartPositionEndPosition 通过给定日期、出发地、目的地进行航班查询请求
	QuireBySetOutDateStartPositionEndPosition(context.Context, *QuireBySetOutDateStartPositionEndPositionReq) (*QuireBySetOutDateStartPositionEndPositionResp, error)
	mustEmbedUnimplementedFlightInquiryServer()
}

// UnimplementedFlightInquiryServer must be embedded to have forward compatible implementations.
type UnimplementedFlightInquiryServer struct {
}

func (UnimplementedFlightInquiryServer) QuireBySetOutDateAndFlightNumber(context.Context, *QuireBySetOutDateAndFlightNumberReq) (*QuireBySetOutDateAndFlightNumberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuireBySetOutDateAndFlightNumber not implemented")
}
func (UnimplementedFlightInquiryServer) QuireBySetOutDateStartPositionEndPosition(context.Context, *QuireBySetOutDateStartPositionEndPositionReq) (*QuireBySetOutDateStartPositionEndPositionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuireBySetOutDateStartPositionEndPosition not implemented")
}
func (UnimplementedFlightInquiryServer) mustEmbedUnimplementedFlightInquiryServer() {}

// UnsafeFlightInquiryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlightInquiryServer will
// result in compilation errors.
type UnsafeFlightInquiryServer interface {
	mustEmbedUnimplementedFlightInquiryServer()
}

func RegisterFlightInquiryServer(s grpc.ServiceRegistrar, srv FlightInquiryServer) {
	s.RegisterService(&FlightInquiry_ServiceDesc, srv)
}

func _FlightInquiry_QuireBySetOutDateAndFlightNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuireBySetOutDateAndFlightNumberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightInquiryServer).QuireBySetOutDateAndFlightNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.flightInquiry/QuireBySetOutDateAndFlightNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightInquiryServer).QuireBySetOutDateAndFlightNumber(ctx, req.(*QuireBySetOutDateAndFlightNumberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightInquiry_QuireBySetOutDateStartPositionEndPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuireBySetOutDateStartPositionEndPositionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightInquiryServer).QuireBySetOutDateStartPositionEndPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.flightInquiry/QuireBySetOutDateStartPositionEndPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightInquiryServer).QuireBySetOutDateStartPositionEndPosition(ctx, req.(*QuireBySetOutDateStartPositionEndPositionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FlightInquiry_ServiceDesc is the grpc.ServiceDesc for FlightInquiry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlightInquiry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.flightInquiry",
	HandlerType: (*FlightInquiryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QuireBySetOutDateAndFlightNumber",
			Handler:    _FlightInquiry_QuireBySetOutDateAndFlightNumber_Handler,
		},
		{
			MethodName: "QuireBySetOutDateStartPositionEndPosition",
			Handler:    _FlightInquiry_QuireBySetOutDateStartPositionEndPosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/flightInquiry/cmd/rpc/pb/flightInquiry.proto",
}
