// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: app/flightInquiry/cmd/rpc/pb/flightInquiry.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FlightInquiryClient is the client API for FlightInquiry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlightInquiryClient interface {
	//QuireBySetOutDateAndFlightNumber 通过给定日期、航班号进行航班查询请求
	QuireBySetOutDateAndFlightNumber(ctx context.Context, in *QuireBySetOutDateAndFlightNumberReq, opts ...grpc.CallOption) (*QuireBySetOutDateAndFlightNumberResp, error)
	//QuireBySetOutDateStartPositionEndPosition 通过给定日期、出发地、目的地进行航班查询请求
	QuireBySetOutDateStartPositionEndPosition(ctx context.Context, in *QuireBySetOutDateStartPositionEndPositionReq, opts ...grpc.CallOption) (*QuireBySetOutDateStartPositionEndPositionResp, error)
	//FlightDetail 通过给定 票id 来获取航班详情
	FlightDetail(ctx context.Context, in *FlightDetailReq, opts ...grpc.CallOption) (*FlightDetailResp, error)
	//GetDiscountFlights 查询折扣航班
	GetDiscountFlights(ctx context.Context, in *GetDiscountFlightsReq, opts ...grpc.CallOption) (*GetDiscountFlightsResp, error)
	//GetFlightsByPriceRange 查询指定价格区间的航班
	GetFlightsByPriceRange(ctx context.Context, in *GetFlightsByPriceRangeReq, opts ...grpc.CallOption) (*GetFlightsByPriceRangeResp, error)
	//GetFlightsByFlightNumber 根据航班号获取航班信息
	GetFlightsByFlightNumber(ctx context.Context, in *GetFlightsByFlightNumberReq, opts ...grpc.CallOption) (*GetFlightsByFlightNumberResp, error)
	//QuireTransferFlights 中转航班查询
	QuireTransferFlights(ctx context.Context, in *QuireTransferFlightsReq, opts ...grpc.CallOption) (*QuireTransferFlightsResp, error)
	//RecommendReturnJourneyByFlightInfo 根据指定航班信息提供返程机票推荐(仅支持直飞)
	RecommendReturnJourneyByFlightInfo(ctx context.Context, in *RecommendReturnJourneyByFlightInfoReq, opts ...grpc.CallOption) (*RecommendReturnJourneyByFlightInfoResp, error)
}

type flightInquiryClient struct {
	cc grpc.ClientConnInterface
}

func NewFlightInquiryClient(cc grpc.ClientConnInterface) FlightInquiryClient {
	return &flightInquiryClient{cc}
}

func (c *flightInquiryClient) QuireBySetOutDateAndFlightNumber(ctx context.Context, in *QuireBySetOutDateAndFlightNumberReq, opts ...grpc.CallOption) (*QuireBySetOutDateAndFlightNumberResp, error) {
	out := new(QuireBySetOutDateAndFlightNumberResp)
	err := c.cc.Invoke(ctx, "/pb.flightInquiry/QuireBySetOutDateAndFlightNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightInquiryClient) QuireBySetOutDateStartPositionEndPosition(ctx context.Context, in *QuireBySetOutDateStartPositionEndPositionReq, opts ...grpc.CallOption) (*QuireBySetOutDateStartPositionEndPositionResp, error) {
	out := new(QuireBySetOutDateStartPositionEndPositionResp)
	err := c.cc.Invoke(ctx, "/pb.flightInquiry/QuireBySetOutDateStartPositionEndPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightInquiryClient) FlightDetail(ctx context.Context, in *FlightDetailReq, opts ...grpc.CallOption) (*FlightDetailResp, error) {
	out := new(FlightDetailResp)
	err := c.cc.Invoke(ctx, "/pb.flightInquiry/FlightDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightInquiryClient) GetDiscountFlights(ctx context.Context, in *GetDiscountFlightsReq, opts ...grpc.CallOption) (*GetDiscountFlightsResp, error) {
	out := new(GetDiscountFlightsResp)
	err := c.cc.Invoke(ctx, "/pb.flightInquiry/GetDiscountFlights", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightInquiryClient) GetFlightsByPriceRange(ctx context.Context, in *GetFlightsByPriceRangeReq, opts ...grpc.CallOption) (*GetFlightsByPriceRangeResp, error) {
	out := new(GetFlightsByPriceRangeResp)
	err := c.cc.Invoke(ctx, "/pb.flightInquiry/GetFlightsByPriceRange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightInquiryClient) GetFlightsByFlightNumber(ctx context.Context, in *GetFlightsByFlightNumberReq, opts ...grpc.CallOption) (*GetFlightsByFlightNumberResp, error) {
	out := new(GetFlightsByFlightNumberResp)
	err := c.cc.Invoke(ctx, "/pb.flightInquiry/GetFlightsByFlightNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightInquiryClient) QuireTransferFlights(ctx context.Context, in *QuireTransferFlightsReq, opts ...grpc.CallOption) (*QuireTransferFlightsResp, error) {
	out := new(QuireTransferFlightsResp)
	err := c.cc.Invoke(ctx, "/pb.flightInquiry/QuireTransferFlights", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightInquiryClient) RecommendReturnJourneyByFlightInfo(ctx context.Context, in *RecommendReturnJourneyByFlightInfoReq, opts ...grpc.CallOption) (*RecommendReturnJourneyByFlightInfoResp, error) {
	out := new(RecommendReturnJourneyByFlightInfoResp)
	err := c.cc.Invoke(ctx, "/pb.flightInquiry/RecommendReturnJourneyByFlightInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightInquiryServer is the server API for FlightInquiry service.
// All implementations must embed UnimplementedFlightInquiryServer
// for forward compatibility
type FlightInquiryServer interface {
	//QuireBySetOutDateAndFlightNumber 通过给定日期、航班号进行航班查询请求
	QuireBySetOutDateAndFlightNumber(context.Context, *QuireBySetOutDateAndFlightNumberReq) (*QuireBySetOutDateAndFlightNumberResp, error)
	//QuireBySetOutDateStartPositionEndPosition 通过给定日期、出发地、目的地进行航班查询请求
	QuireBySetOutDateStartPositionEndPosition(context.Context, *QuireBySetOutDateStartPositionEndPositionReq) (*QuireBySetOutDateStartPositionEndPositionResp, error)
	//FlightDetail 通过给定 票id 来获取航班详情
	FlightDetail(context.Context, *FlightDetailReq) (*FlightDetailResp, error)
	//GetDiscountFlights 查询折扣航班
	GetDiscountFlights(context.Context, *GetDiscountFlightsReq) (*GetDiscountFlightsResp, error)
	//GetFlightsByPriceRange 查询指定价格区间的航班
	GetFlightsByPriceRange(context.Context, *GetFlightsByPriceRangeReq) (*GetFlightsByPriceRangeResp, error)
	//GetFlightsByFlightNumber 根据航班号获取航班信息
	GetFlightsByFlightNumber(context.Context, *GetFlightsByFlightNumberReq) (*GetFlightsByFlightNumberResp, error)
	//QuireTransferFlights 中转航班查询
	QuireTransferFlights(context.Context, *QuireTransferFlightsReq) (*QuireTransferFlightsResp, error)
	//RecommendReturnJourneyByFlightInfo 根据指定航班信息提供返程机票推荐(仅支持直飞)
	RecommendReturnJourneyByFlightInfo(context.Context, *RecommendReturnJourneyByFlightInfoReq) (*RecommendReturnJourneyByFlightInfoResp, error)
	mustEmbedUnimplementedFlightInquiryServer()
}

// UnimplementedFlightInquiryServer must be embedded to have forward compatible implementations.
type UnimplementedFlightInquiryServer struct {
}

func (UnimplementedFlightInquiryServer) QuireBySetOutDateAndFlightNumber(context.Context, *QuireBySetOutDateAndFlightNumberReq) (*QuireBySetOutDateAndFlightNumberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuireBySetOutDateAndFlightNumber not implemented")
}
func (UnimplementedFlightInquiryServer) QuireBySetOutDateStartPositionEndPosition(context.Context, *QuireBySetOutDateStartPositionEndPositionReq) (*QuireBySetOutDateStartPositionEndPositionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuireBySetOutDateStartPositionEndPosition not implemented")
}
func (UnimplementedFlightInquiryServer) FlightDetail(context.Context, *FlightDetailReq) (*FlightDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlightDetail not implemented")
}
func (UnimplementedFlightInquiryServer) GetDiscountFlights(context.Context, *GetDiscountFlightsReq) (*GetDiscountFlightsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiscountFlights not implemented")
}
func (UnimplementedFlightInquiryServer) GetFlightsByPriceRange(context.Context, *GetFlightsByPriceRangeReq) (*GetFlightsByPriceRangeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlightsByPriceRange not implemented")
}
func (UnimplementedFlightInquiryServer) GetFlightsByFlightNumber(context.Context, *GetFlightsByFlightNumberReq) (*GetFlightsByFlightNumberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlightsByFlightNumber not implemented")
}
func (UnimplementedFlightInquiryServer) QuireTransferFlights(context.Context, *QuireTransferFlightsReq) (*QuireTransferFlightsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuireTransferFlights not implemented")
}
func (UnimplementedFlightInquiryServer) RecommendReturnJourneyByFlightInfo(context.Context, *RecommendReturnJourneyByFlightInfoReq) (*RecommendReturnJourneyByFlightInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecommendReturnJourneyByFlightInfo not implemented")
}
func (UnimplementedFlightInquiryServer) mustEmbedUnimplementedFlightInquiryServer() {}

// UnsafeFlightInquiryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlightInquiryServer will
// result in compilation errors.
type UnsafeFlightInquiryServer interface {
	mustEmbedUnimplementedFlightInquiryServer()
}

func RegisterFlightInquiryServer(s grpc.ServiceRegistrar, srv FlightInquiryServer) {
	s.RegisterService(&FlightInquiry_ServiceDesc, srv)
}

func _FlightInquiry_QuireBySetOutDateAndFlightNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuireBySetOutDateAndFlightNumberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightInquiryServer).QuireBySetOutDateAndFlightNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.flightInquiry/QuireBySetOutDateAndFlightNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightInquiryServer).QuireBySetOutDateAndFlightNumber(ctx, req.(*QuireBySetOutDateAndFlightNumberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightInquiry_QuireBySetOutDateStartPositionEndPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuireBySetOutDateStartPositionEndPositionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightInquiryServer).QuireBySetOutDateStartPositionEndPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.flightInquiry/QuireBySetOutDateStartPositionEndPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightInquiryServer).QuireBySetOutDateStartPositionEndPosition(ctx, req.(*QuireBySetOutDateStartPositionEndPositionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightInquiry_FlightDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightInquiryServer).FlightDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.flightInquiry/FlightDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightInquiryServer).FlightDetail(ctx, req.(*FlightDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightInquiry_GetDiscountFlights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscountFlightsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightInquiryServer).GetDiscountFlights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.flightInquiry/GetDiscountFlights",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightInquiryServer).GetDiscountFlights(ctx, req.(*GetDiscountFlightsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightInquiry_GetFlightsByPriceRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlightsByPriceRangeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightInquiryServer).GetFlightsByPriceRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.flightInquiry/GetFlightsByPriceRange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightInquiryServer).GetFlightsByPriceRange(ctx, req.(*GetFlightsByPriceRangeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightInquiry_GetFlightsByFlightNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlightsByFlightNumberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightInquiryServer).GetFlightsByFlightNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.flightInquiry/GetFlightsByFlightNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightInquiryServer).GetFlightsByFlightNumber(ctx, req.(*GetFlightsByFlightNumberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightInquiry_QuireTransferFlights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuireTransferFlightsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightInquiryServer).QuireTransferFlights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.flightInquiry/QuireTransferFlights",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightInquiryServer).QuireTransferFlights(ctx, req.(*QuireTransferFlightsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightInquiry_RecommendReturnJourneyByFlightInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendReturnJourneyByFlightInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightInquiryServer).RecommendReturnJourneyByFlightInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.flightInquiry/RecommendReturnJourneyByFlightInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightInquiryServer).RecommendReturnJourneyByFlightInfo(ctx, req.(*RecommendReturnJourneyByFlightInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FlightInquiry_ServiceDesc is the grpc.ServiceDesc for FlightInquiry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlightInquiry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.flightInquiry",
	HandlerType: (*FlightInquiryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QuireBySetOutDateAndFlightNumber",
			Handler:    _FlightInquiry_QuireBySetOutDateAndFlightNumber_Handler,
		},
		{
			MethodName: "QuireBySetOutDateStartPositionEndPosition",
			Handler:    _FlightInquiry_QuireBySetOutDateStartPositionEndPosition_Handler,
		},
		{
			MethodName: "FlightDetail",
			Handler:    _FlightInquiry_FlightDetail_Handler,
		},
		{
			MethodName: "GetDiscountFlights",
			Handler:    _FlightInquiry_GetDiscountFlights_Handler,
		},
		{
			MethodName: "GetFlightsByPriceRange",
			Handler:    _FlightInquiry_GetFlightsByPriceRange_Handler,
		},
		{
			MethodName: "GetFlightsByFlightNumber",
			Handler:    _FlightInquiry_GetFlightsByFlightNumber_Handler,
		},
		{
			MethodName: "QuireTransferFlights",
			Handler:    _FlightInquiry_QuireTransferFlights_Handler,
		},
		{
			MethodName: "RecommendReturnJourneyByFlightInfo",
			Handler:    _FlightInquiry_RecommendReturnJourneyByFlightInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/flightInquiry/cmd/rpc/pb/flightInquiry.proto",
}
