// Code generated by goctl. DO NOT EDIT!
// Source: userCenter.proto

package server

import (
	"context"

	"uranus/app/userCenter/cmd/rpc/internal/logic"
	"uranus/app/userCenter/cmd/rpc/internal/svc"
	"uranus/app/userCenter/cmd/rpc/pb"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUsercenterServer
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UsercenterServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UsercenterServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoReq) (*pb.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UsercenterServer) GetUserAuthByUserId(ctx context.Context, in *pb.GetUserAuthByUserIdReq) (*pb.GetUserAuthByUserIdResp, error) {
	l := logic.NewGetUserAuthByUserIdLogic(ctx, s.svcCtx)
	return l.GetUserAuthByUserId(in)
}

func (s *UsercenterServer) GetUserAuthByAuthKey(ctx context.Context, in *pb.GetUserAuthByAuthKeyReq) (*pb.GetUserAuthByAuthKeyResp, error) {
	l := logic.NewGetUserAuthByAuthKeyLogic(ctx, s.svcCtx)
	return l.GetUserAuthByAuthKey(in)
}

func (s *UsercenterServer) GetUserMoney(ctx context.Context, in *pb.GetUserMoneyReq) (*pb.GetUserMoneyResp, error) {
	l := logic.NewGetUserMoneyLogic(ctx, s.svcCtx)
	return l.GetUserMoney(in)
}

func (s *UsercenterServer) UpdateUserWallet(ctx context.Context, in *pb.UpdateUserWalletReq) (*pb.UpdateUserWalletResp, error) {
	l := logic.NewUpdateUserWalletLogic(ctx, s.svcCtx)
	return l.UpdateUserWallet(in)
}

func (s *UsercenterServer) AddMoney(ctx context.Context, in *pb.AddMoneyReq) (*pb.AddMoneyResp, error) {
	l := logic.NewAddMoneyLogic(ctx, s.svcCtx)
	return l.AddMoney(in)
}

func (s *UsercenterServer) DeductMoney(ctx context.Context, in *pb.DeductMoneyReq) (*pb.DeductMoneyResp, error) {
	l := logic.NewDeductMoneyLogic(ctx, s.svcCtx)
	return l.DeductMoney(in)
}

func (s *UsercenterServer) DeductMontyRollBack(ctx context.Context, in *pb.DeductMoneyReq) (*pb.DeductMoneyResp, error) {
	l := logic.NewDeductMontyRollBackLogic(ctx, s.svcCtx)
	return l.DeductMontyRollBack(in)
}
