// Code generated by goctl. DO NOT EDIT!
// Source: flightInquiry.proto

package flightinquiry

import (
	"context"

	"uranus/app/flightInquiry/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChangeInfo                                    = pb.ChangeInfo
	FlightDetailReq                               = pb.FlightDetailReq
	FlightDetailResp                              = pb.FlightDetailResp
	FlightInfo                                    = pb.FlightInfo
	QuireBySetOutDateAndFlightNumberReq           = pb.QuireBySetOutDateAndFlightNumberReq
	QuireBySetOutDateAndFlightNumberResp          = pb.QuireBySetOutDateAndFlightNumberResp
	QuireBySetOutDateStartPositionEndPositionReq  = pb.QuireBySetOutDateStartPositionEndPositionReq
	QuireBySetOutDateStartPositionEndPositionResp = pb.QuireBySetOutDateStartPositionEndPositionResp
	RefundInfo                                    = pb.RefundInfo
	TimeFee                                       = pb.TimeFee

	FlightInquiry interface {
		// QuireBySetOutDateAndFlightNumber 通过给定日期、航班号进行航班查询请求
		QuireBySetOutDateAndFlightNumber(ctx context.Context, in *QuireBySetOutDateAndFlightNumberReq, opts ...grpc.CallOption) (*QuireBySetOutDateAndFlightNumberResp, error)
		// QuireBySetOutDateStartPositionEndPosition 通过给定日期、出发地、目的地进行航班查询请求
		QuireBySetOutDateStartPositionEndPosition(ctx context.Context, in *QuireBySetOutDateStartPositionEndPositionReq, opts ...grpc.CallOption) (*QuireBySetOutDateStartPositionEndPositionResp, error)
		// FlightDetail 通过给定 票id 来获取航班详情
		FlightDetail(ctx context.Context, in *FlightDetailReq, opts ...grpc.CallOption) (*FlightDetailResp, error)
	}

	defaultFlightInquiry struct {
		cli zrpc.Client
	}
)

func NewFlightInquiry(cli zrpc.Client) FlightInquiry {
	return &defaultFlightInquiry{
		cli: cli,
	}
}

// QuireBySetOutDateAndFlightNumber 通过给定日期、航班号进行航班查询请求
func (m *defaultFlightInquiry) QuireBySetOutDateAndFlightNumber(ctx context.Context, in *QuireBySetOutDateAndFlightNumberReq, opts ...grpc.CallOption) (*QuireBySetOutDateAndFlightNumberResp, error) {
	client := pb.NewFlightInquiryClient(m.cli.Conn())
	return client.QuireBySetOutDateAndFlightNumber(ctx, in, opts...)
}

// QuireBySetOutDateStartPositionEndPosition 通过给定日期、出发地、目的地进行航班查询请求
func (m *defaultFlightInquiry) QuireBySetOutDateStartPositionEndPosition(ctx context.Context, in *QuireBySetOutDateStartPositionEndPositionReq, opts ...grpc.CallOption) (*QuireBySetOutDateStartPositionEndPositionResp, error) {
	client := pb.NewFlightInquiryClient(m.cli.Conn())
	return client.QuireBySetOutDateStartPositionEndPosition(ctx, in, opts...)
}

// FlightDetail 通过给定 票id 来获取航班详情
func (m *defaultFlightInquiry) FlightDetail(ctx context.Context, in *FlightDetailReq, opts ...grpc.CallOption) (*FlightDetailResp, error) {
	client := pb.NewFlightInquiryClient(m.cli.Conn())
	return client.FlightDetail(ctx, in, opts...)
}
