// Code generated by goctl. DO NOT EDIT!
// Source: flightInquiry.proto

package flightinquiry

import (
	"context"

	"uranus/app/flightInquiry/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChangeInfo                                    = pb.ChangeInfo
	FlightInfo                                    = pb.FlightInfo
	QuireBySetOutTimeAndFlightNumberReq           = pb.QuireBySetOutTimeAndFlightNumberReq
	QuireBySetOutTimeAndFlightNumberResp          = pb.QuireBySetOutTimeAndFlightNumberResp
	QuireBySetOutTimeStartPositionEndPositionReq  = pb.QuireBySetOutTimeStartPositionEndPositionReq
	QuireBySetOutTimeStartPositionEndPositionResp = pb.QuireBySetOutTimeStartPositionEndPositionResp
	RefundInfo                                    = pb.RefundInfo
	TimeFee                                       = pb.TimeFee

	FlightInquiry interface {
		//  QuireBySetOutTimeAndFlightNumber 通过给定日期、航班号进行航班查询请求
		QuireBySetOutTimeAndFlightNumber(ctx context.Context, in *QuireBySetOutTimeAndFlightNumberReq, opts ...grpc.CallOption) (*QuireBySetOutTimeAndFlightNumberResp, error)
		//  QuireBySetOutTimeStartPositionEndPosition 通过给定日期、出发地、目的地进行航班查询请求
		QuireBySetOutTimeStartPositionEndPosition(ctx context.Context, in *QuireBySetOutTimeStartPositionEndPositionReq, opts ...grpc.CallOption) (*QuireBySetOutTimeStartPositionEndPositionResp, error)
	}

	defaultFlightInquiry struct {
		cli zrpc.Client
	}
)

func NewFlightInquiry(cli zrpc.Client) FlightInquiry {
	return &defaultFlightInquiry{
		cli: cli,
	}
}

//  QuireBySetOutTimeAndFlightNumber 通过给定日期、航班号进行航班查询请求
func (m *defaultFlightInquiry) QuireBySetOutTimeAndFlightNumber(ctx context.Context, in *QuireBySetOutTimeAndFlightNumberReq, opts ...grpc.CallOption) (*QuireBySetOutTimeAndFlightNumberResp, error) {
	client := pb.NewFlightInquiryClient(m.cli.Conn())
	return client.QuireBySetOutTimeAndFlightNumber(ctx, in, opts...)
}

//  QuireBySetOutTimeStartPositionEndPosition 通过给定日期、出发地、目的地进行航班查询请求
func (m *defaultFlightInquiry) QuireBySetOutTimeStartPositionEndPosition(ctx context.Context, in *QuireBySetOutTimeStartPositionEndPositionReq, opts ...grpc.CallOption) (*QuireBySetOutTimeStartPositionEndPositionResp, error) {
	client := pb.NewFlightInquiryClient(m.cli.Conn())
	return client.QuireBySetOutTimeStartPositionEndPosition(ctx, in, opts...)
}
