// Code generated by goctl. DO NOT EDIT.
package types

type RefundInfo struct {
	Time1 string `json:"time1"`
	Fee1  uint64 `json:"fee1"`
	Time2 string `json:"time2"`
	Fee2  uint64 `json:"fee2"`
	Time3 string `json:"time3"`
	Fee3  uint64 `json:"fee3"`
	Time4 string `json:"time4"`
	Fee4  uint64 `json:"fee4"`
	Time5 string `json:"time5,optional"`
	Fee5  uint64 `json:"fee5,optional"`
}

type ChangeInfo struct {
	Time1 string `json:"time1"`
	Fee1  uint64 `json:"fee1"`
	Time2 string `json:"time2"`
	Fee2  uint64 `json:"fee2"`
	Time3 string `json:"time3"`
	Fee3  uint64 `json:"fee3"`
	Time4 string `json:"time4"`
	Fee4  uint64 `json:"fee4"`
	Time5 string `json:"time5,optional"`
	Fee5  uint64 `json:"fee5,optional"`
}

type Flightinfo struct {
	FlightNumber   string `json:"flightNumber"`
	SetOutDate     string `json:"setOutDate"`
	IsFirstClass   bool   `json:"isFirstClass"`
	Price          uint64 `json:"price"`
	Discount       int64  `json:"discount"`
	Surplus        int64  `json:"surplus"`
	Punctuality    uint32 `json:"punctuality"`
	DepartPosition string `json:"departPosition"`
	DepartTime     string `json:"departTime"`
	ArrivePosition string `json:"arrivePosition"`
	ArriveTime     string `json:"arriveTime"`
	RefundInfo
	ChangeInfo
}

type QuireBySetOutDateAndFlightNumberReq struct {
	FlightNumber string `json:"flightNumber"`
	SetOutDate   string `json:"setOutDate"`
}

type QuireBySetOutDateAndFlightNumberResp struct {
	Flightinfo
}

type QuireBySetOutDateStartPositionEndPositionReq struct {
	SetOutDate     string `json:"setOutDate"`
	DepartPosition string `json:"departPosition"`
	ArrivePosition string `json:"arrivePosition"`
}

type QuireBySetOutDateStartPositionEndPositionResp struct {
	Flightinfo
}
