// Code generated by goctl. DO NOT EDIT.
package types

type TF struct {
	Time string `json:"time"`
	Fee  uint64 `json:"fee"`
}

type RefundInfo struct {
	TFs []TF `json:"tfs"`
}

type ChangeInfo struct {
	TFs []TF `json:"tfs"`
}

type Flightinfo struct {
	FlightNumber   string     `json:"flightNumber"`
	SetOutDate     string     `json:"setOutDate"`
	IsFirstClass   bool       `json:"isFirstClass"`
	Price          uint64     `json:"price"`
	Discount       int64      `json:"discount"`
	Surplus        int64      `json:"surplus"`
	Punctuality    uint32     `json:"punctuality"`
	DepartPosition string     `json:"departPosition"`
	DepartTime     string     `json:"departTime"`
	ArrivePosition string     `json:"arrivePosition"`
	ArriveTime     string     `json:"arriveTime"`
	RefundInfo     RefundInfo `json:"refundInfo"`
	ChangeInfo     RefundInfo `json:"changeInfo"`
}

type QuireBySetOutDateAndFlightNumberReq struct {
	FlightNumber string `json:"flightNumber"`
	SetOutDate   string `json:"setOutDate"`
}

type QuireBySetOutDateAndFlightNumberResp struct {
	Flightinfos []*Flightinfo `json:"flightinfos"`
}

type QuireBySetOutDateStartPositionEndPositionReq struct {
	SetOutDate     string `json:"setOutDate"`
	DepartPosition string `json:"departPosition"`
	ArrivePosition string `json:"arrivePosition"`
}

type QuireBySetOutDateStartPositionEndPositionResp struct {
	Flightinfos []*Flightinfo `json:"flightinfos"`
}
