// Code generated by goctl. DO NOT EDIT.
package types

type TF struct {
	Time string `json:"time"`
	Fee  uint64 `json:"fee"`
}

type RefundInfo struct {
	TFs []TF `json:"tfs"`
}

type ChangeInfo struct {
	TFs []TF `json:"tfs"`
}

type Flightinfo struct {
	FlightInfoID   int64      `json:"flightInfoId"`
	FlightNumber   string     `json:"flightNumber"`
	FlightType     string     `json:"flightType"`
	SetOutDate     string     `json:"setOutDate"`
	IsFirstClass   bool       `json:"isFirstClass"`
	SpaceID        int64      `json:"spaceId"`
	Price          uint64     `json:"price"`
	Discount       int64      `json:"discount"`
	Surplus        int64      `json:"surplus"`
	Punctuality    uint32     `json:"punctuality"`
	DepartPosition string     `json:"departPosition"`
	DepartTime     string     `json:"departTime"`
	ArrivePosition string     `json:"arrivePosition"`
	ArriveTime     string     `json:"arriveTime"`
	RefundInfo     RefundInfo `json:"refundInfo"`
	ChangeInfo     RefundInfo `json:"changeInfo"`
}

type UniqFlightWithSpaces struct {
	FlightInfoID       int64        `json:"flightInfoId"`
	SpacesOfFlightInfo []Flightinfo `json:"spacesOfFlightInfo"`
}

type TransferFlights struct {
	UniqFlightWithSpaceses []*UniqFlightWithSpaces `json:"uniqFlightWithSpaceses"`
}

type QuireBySetOutDateAndFlightNumberReq struct {
	FlightNumber string `json:"flightNumber"`
	SetOutDate   string `json:"setOutDate"`
}

type QuireBySetOutDateAndFlightNumberResp struct {
	UniqFlightWithSpaces []*UniqFlightWithSpaces `json:"uniqFlightWithSpaces"`
}

type QuireBySetOutDateStartPositionEndPositionReq struct {
	SetOutDate     string `json:"setOutDate"`
	DepartPosition string `json:"departPosition"`
	ArrivePosition string `json:"arrivePosition"`
}

type QuireBySetOutDateStartPositionEndPositionResp struct {
	UniqFlightWithSpaces []*UniqFlightWithSpaces `json:"uniqFlightWithSpaces"`
}

type GetDiscountFlightsReq struct {
	DepartPosition string `json:"departPosition"`
	ArrivePosition string `json:"arrivePosition"`
	SelectedDate   string `json:"selectedDate"`
	Days           int64  `json:"days"`
	Num            int64  `json:"num"`
}

type GetDiscountFlightsResp struct {
	UniqFlightWithSpaces []*UniqFlightWithSpaces `json:"uniqFlightWithSpaces"`
}

type GetFlightsByFlightNumberReq struct {
	FlightNumber string `json:"flightNumber"`
	Days         int64  `json:"days"`
	Num          int64  `json:"num"`
}

type GetFlightsByFlightNumberResp struct {
	UniqFlightWithSpaces []*UniqFlightWithSpaces `json:"uniqFlightWithSpaces"`
}

type GetFlightsByPriceRangeReq struct {
	DepartPosition string `json:"departPosition"`
	ArrivePosition string `json:"arrivePosition"`
	MaxPrice       int64  `json:"maxPrice"`
	MinPrice       int64  `json:"minPrice"`
	SelectedDate   string `json:"selectedDate"`
	Days           int64  `json:"days"`
	Num            int64  `json:"num"`
}

type GetFlightsByPriceRangeResp struct {
	UniqFlightWithSpaces []*UniqFlightWithSpaces `json:"uniqFlightWithSpaces"`
}

type QuireTransferFlightsReq struct {
	DepartPosition string `json:"departPosition"`
	ArrivePosition string `json:"arrivePosition"`
	SetOutDate     string `json:"setOutDate"`
}

type QuireTransferFlightsResp struct {
	Transfers []TransferFlights `json:"transfers"`
}

type RecommendReturnJourneyByFlightInfoReq struct {
	FlightInfoID int64  `json:"flightInfoId"`
	SelectedDate string `json:"selectedDate"`
}

type RecommendReturnJourneyByFlightInfoResp struct {
	UniqFlightWithSpaces []*UniqFlightWithSpaces `json:"uniqFlightWithSpaces"`
}

type GetFlightDetailByTicketIDReq struct {
	TicketID int64 `json:"ticketId"`
}

type GetFlightDetailByTicketIDResp struct {
	Flightinfo Flightinfo `json:"flightinfo"`
}
