// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.2
// source: app/flightReservation/cmd/rpc/pb/flightReservation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 预定机票请求
type BookAirTicketsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户的id
	UserID int64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	// 航班号，例如MU5735
	FlightNumber string `protobuf:"bytes,2,opt,name=FlightNumber,proto3" json:"FlightNumber,omitempty"`
	// 出发日期
	SetOutDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=SetOutDate,proto3" json:"SetOutDate,omitempty"`
	// 是否为头等舱/商务舱
	IsFirstClass bool `protobuf:"varint,4,opt,name=IsFirstClass,proto3" json:"IsFirstClass,omitempty"`
	// 起飞地点
	DepartPosition string `protobuf:"bytes,5,opt,name=DepartPosition,proto3" json:"DepartPosition,omitempty"`
	// 起飞时间
	DepartTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=DepartTime,proto3" json:"DepartTime,omitempty"`
	// 降落地点
	ArrivePosition string `protobuf:"bytes,7,opt,name=ArrivePosition,proto3" json:"ArrivePosition,omitempty"`
	// 降落时间
	ArriveTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ArriveTime,proto3" json:"ArriveTime,omitempty"`
}

func (x *BookAirTicketsReq) Reset() {
	*x = BookAirTicketsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookAirTicketsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookAirTicketsReq) ProtoMessage() {}

func (x *BookAirTicketsReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookAirTicketsReq.ProtoReflect.Descriptor instead.
func (*BookAirTicketsReq) Descriptor() ([]byte, []int) {
	return file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_rawDescGZIP(), []int{0}
}

func (x *BookAirTicketsReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *BookAirTicketsReq) GetFlightNumber() string {
	if x != nil {
		return x.FlightNumber
	}
	return ""
}

func (x *BookAirTicketsReq) GetSetOutDate() *timestamppb.Timestamp {
	if x != nil {
		return x.SetOutDate
	}
	return nil
}

func (x *BookAirTicketsReq) GetIsFirstClass() bool {
	if x != nil {
		return x.IsFirstClass
	}
	return false
}

func (x *BookAirTicketsReq) GetDepartPosition() string {
	if x != nil {
		return x.DepartPosition
	}
	return ""
}

func (x *BookAirTicketsReq) GetDepartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartTime
	}
	return nil
}

func (x *BookAirTicketsReq) GetArrivePosition() string {
	if x != nil {
		return x.ArrivePosition
	}
	return ""
}

func (x *BookAirTicketsReq) GetArriveTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ArriveTime
	}
	return nil
}

// 预定机票响应
type BookAirTicketsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderSn string `protobuf:"bytes,2,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
}

func (x *BookAirTicketsResp) Reset() {
	*x = BookAirTicketsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookAirTicketsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookAirTicketsResp) ProtoMessage() {}

func (x *BookAirTicketsResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookAirTicketsResp.ProtoReflect.Descriptor instead.
func (*BookAirTicketsResp) Descriptor() ([]byte, []int) {
	return file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_rawDescGZIP(), []int{1}
}

func (x *BookAirTicketsResp) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

// 退票请求
type RefundAirTicketsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户的id
	UserID int64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	// 用户拥有的对应票id
	TicketID uint64 `protobuf:"varint,2,opt,name=TicketID,proto3" json:"TicketID,omitempty"`
}

func (x *RefundAirTicketsReq) Reset() {
	*x = RefundAirTicketsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundAirTicketsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundAirTicketsReq) ProtoMessage() {}

func (x *RefundAirTicketsReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundAirTicketsReq.ProtoReflect.Descriptor instead.
func (*RefundAirTicketsReq) Descriptor() ([]byte, []int) {
	return file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_rawDescGZIP(), []int{2}
}

func (x *RefundAirTicketsReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *RefundAirTicketsReq) GetTicketID() uint64 {
	if x != nil {
		return x.TicketID
	}
	return 0
}

// 退票响应
type RefundAirTicketsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefundAirTicketsResp) Reset() {
	*x = RefundAirTicketsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundAirTicketsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundAirTicketsResp) ProtoMessage() {}

func (x *RefundAirTicketsResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundAirTicketsResp.ProtoReflect.Descriptor instead.
func (*RefundAirTicketsResp) Descriptor() ([]byte, []int) {
	return file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_rawDescGZIP(), []int{3}
}

// 改票请求
type ChangeAirTicketsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户的id
	UserID int64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	// 用户拥有的对应票id
	TicketID uint64 `protobuf:"varint,2,opt,name=TicketID,proto3" json:"TicketID,omitempty"`
	// 目标舱位id
	SpaceID uint64 `protobuf:"varint,3,opt,name=SpaceID,proto3" json:"SpaceID,omitempty"`
}

func (x *ChangeAirTicketsReq) Reset() {
	*x = ChangeAirTicketsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeAirTicketsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeAirTicketsReq) ProtoMessage() {}

func (x *ChangeAirTicketsReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeAirTicketsReq.ProtoReflect.Descriptor instead.
func (*ChangeAirTicketsReq) Descriptor() ([]byte, []int) {
	return file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeAirTicketsReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ChangeAirTicketsReq) GetTicketID() uint64 {
	if x != nil {
		return x.TicketID
	}
	return 0
}

func (x *ChangeAirTicketsReq) GetSpaceID() uint64 {
	if x != nil {
		return x.SpaceID
	}
	return 0
}

// 改票响应
type ChangeAirTicketsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeAirTicketsResp) Reset() {
	*x = ChangeAirTicketsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeAirTicketsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeAirTicketsResp) ProtoMessage() {}

func (x *ChangeAirTicketsResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeAirTicketsResp.ProtoReflect.Descriptor instead.
func (*ChangeAirTicketsResp) Descriptor() ([]byte, []int) {
	return file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_rawDescGZIP(), []int{5}
}

var File_app_flightReservation_cmd_rpc_pb_flightReservation_proto protoreflect.FileDescriptor

var file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_rawDesc = []byte{
	0x0a, 0x38, 0x61, 0x70, 0x70, 0x2f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x62, 0x2f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xf7, 0x02, 0x0a, 0x11, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x69, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a,
	0x0c, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x3a, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0a, 0x53, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x49, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x49, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x44, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x0a, 0x44, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x44, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x41, 0x72, 0x72, 0x69, 0x76, 0x65, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x41,
	0x72, 0x72, 0x69, 0x76, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3a, 0x0a,
	0x0a, 0x41, 0x72, 0x72, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x41,
	0x72, 0x72, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x42, 0x6f, 0x6f,
	0x6b, 0x41, 0x69, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x22, 0x49, 0x0a, 0x13, 0x52, 0x65, 0x66,
	0x75, 0x6e, 0x64, 0x41, 0x69, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x49, 0x44, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x41, 0x69,
	0x72, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x63, 0x0a, 0x13,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x69, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49,
	0x44, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x69, 0x72, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x32, 0xe2, 0x01, 0x0a, 0x11, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x3f, 0x0a, 0x0e, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x69, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x69, 0x72, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x41, 0x69, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x45, 0x0a, 0x10, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x41, 0x69, 0x72, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64,
	0x41, 0x69, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x41, 0x69, 0x72, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x45, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x41, 0x69, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x17, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x69, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x41, 0x69, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_rawDescOnce sync.Once
	file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_rawDescData = file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_rawDesc
)

func file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_rawDescGZIP() []byte {
	file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_rawDescOnce.Do(func() {
		file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_rawDescData)
	})
	return file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_rawDescData
}

var file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_goTypes = []interface{}{
	(*BookAirTicketsReq)(nil),     // 0: pb.BookAirTicketsReq
	(*BookAirTicketsResp)(nil),    // 1: pb.BookAirTicketsResp
	(*RefundAirTicketsReq)(nil),   // 2: pb.RefundAirTicketsReq
	(*RefundAirTicketsResp)(nil),  // 3: pb.RefundAirTicketsResp
	(*ChangeAirTicketsReq)(nil),   // 4: pb.ChangeAirTicketsReq
	(*ChangeAirTicketsResp)(nil),  // 5: pb.ChangeAirTicketsResp
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_depIdxs = []int32{
	6, // 0: pb.BookAirTicketsReq.SetOutDate:type_name -> google.protobuf.Timestamp
	6, // 1: pb.BookAirTicketsReq.DepartTime:type_name -> google.protobuf.Timestamp
	6, // 2: pb.BookAirTicketsReq.ArriveTime:type_name -> google.protobuf.Timestamp
	0, // 3: pb.flightReservation.BookAirTickets:input_type -> pb.BookAirTicketsReq
	2, // 4: pb.flightReservation.RefundAirTickets:input_type -> pb.RefundAirTicketsReq
	4, // 5: pb.flightReservation.ChangeAirTickets:input_type -> pb.ChangeAirTicketsReq
	1, // 6: pb.flightReservation.BookAirTickets:output_type -> pb.BookAirTicketsResp
	3, // 7: pb.flightReservation.RefundAirTickets:output_type -> pb.RefundAirTicketsResp
	5, // 8: pb.flightReservation.ChangeAirTickets:output_type -> pb.ChangeAirTicketsResp
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_init() }
func file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_init() {
	if File_app_flightReservation_cmd_rpc_pb_flightReservation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookAirTicketsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookAirTicketsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundAirTicketsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundAirTicketsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeAirTicketsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeAirTicketsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_goTypes,
		DependencyIndexes: file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_depIdxs,
		MessageInfos:      file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_msgTypes,
	}.Build()
	File_app_flightReservation_cmd_rpc_pb_flightReservation_proto = out.File
	file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_rawDesc = nil
	file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_goTypes = nil
	file_app_flightReservation_cmd_rpc_pb_flightReservation_proto_depIdxs = nil
}
