// Code generated by goctl. DO NOT EDIT!
// Source: flightInquiry.proto

package server

import (
	"context"

	"uranus/app/flightInquiry/cmd/rpc/internal/logic"
	"uranus/app/flightInquiry/cmd/rpc/internal/svc"
	"uranus/app/flightInquiry/cmd/rpc/pb"
)

type FlightInquiryServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFlightInquiryServer
}

func NewFlightInquiryServer(svcCtx *svc.ServiceContext) *FlightInquiryServer {
	return &FlightInquiryServer{
		svcCtx: svcCtx,
	}
}

// QuireBySetOutDateAndFlightNumber 通过给定日期、航班号进行航班查询请求
func (s *FlightInquiryServer) QuireBySetOutDateAndFlightNumber(ctx context.Context, in *pb.QuireBySetOutDateAndFlightNumberReq) (*pb.QuireBySetOutDateAndFlightNumberResp, error) {
	l := logic.NewQuireBySetOutDateAndFlightNumberLogic(ctx, s.svcCtx)
	return l.QuireBySetOutDateAndFlightNumber(in)
}

// QuireBySetOutDateStartPositionEndPosition 通过给定日期、出发地、目的地进行航班查询请求
func (s *FlightInquiryServer) QuireBySetOutDateStartPositionEndPosition(ctx context.Context, in *pb.QuireBySetOutDateStartPositionEndPositionReq) (*pb.QuireBySetOutDateStartPositionEndPositionResp, error) {
	l := logic.NewQuireBySetOutDateStartPositionEndPositionLogic(ctx, s.svcCtx)
	return l.QuireBySetOutDateStartPositionEndPosition(in)
}
