// Code generated by goctl. DO NOT EDIT!
// Source: flightInquiry.proto

package server

import (
	"context"

	"uranus/app/flightInquiry/cmd/rpc/internal/logic"
	"uranus/app/flightInquiry/cmd/rpc/internal/svc"
	"uranus/app/flightInquiry/cmd/rpc/pb"
)

type FlightInquiryServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFlightInquiryServer
}

func NewFlightInquiryServer(svcCtx *svc.ServiceContext) *FlightInquiryServer {
	return &FlightInquiryServer{
		svcCtx: svcCtx,
	}
}

// QuireBySetOutDateAndFlightNumber 通过给定日期、航班号进行航班查询请求
func (s *FlightInquiryServer) QuireBySetOutDateAndFlightNumber(ctx context.Context, in *pb.QuireBySetOutDateAndFlightNumberReq) (*pb.QuireBySetOutDateAndFlightNumberResp, error) {
	l := logic.NewQuireBySetOutDateAndFlightNumberLogic(ctx, s.svcCtx)
	return l.QuireBySetOutDateAndFlightNumber(in)
}

// QuireBySetOutDateStartPositionEndPosition 通过给定日期、出发地、目的地进行航班查询请求
func (s *FlightInquiryServer) QuireBySetOutDateStartPositionEndPosition(ctx context.Context, in *pb.QuireBySetOutDateStartPositionEndPositionReq) (*pb.QuireBySetOutDateStartPositionEndPositionResp, error) {
	l := logic.NewQuireBySetOutDateStartPositionEndPositionLogic(ctx, s.svcCtx)
	return l.QuireBySetOutDateStartPositionEndPosition(in)
}

// FlightDetail 通过给定 票id 来获取航班详情
func (s *FlightInquiryServer) FlightDetail(ctx context.Context, in *pb.FlightDetailReq) (*pb.FlightDetailResp, error) {
	l := logic.NewFlightDetailLogic(ctx, s.svcCtx)
	return l.FlightDetail(in)
}

// GetDiscountFlights 查询折扣航班
func (s *FlightInquiryServer) GetDiscountFlights(ctx context.Context, in *pb.GetDiscountFlightsReq) (*pb.GetDiscountFlightsResp, error) {
	l := logic.NewGetDiscountFlightsLogic(ctx, s.svcCtx)
	return l.GetDiscountFlights(in)
}

// GetFlightsByPriceRange 查询指定价格区间的航班
func (s *FlightInquiryServer) GetFlightsByPriceRange(ctx context.Context, in *pb.GetFlightsByPriceRangeReq) (*pb.GetFlightsByPriceRangeResp, error) {
	l := logic.NewGetFlightsByPriceRangeLogic(ctx, s.svcCtx)
	return l.GetFlightsByPriceRange(in)
}

// GetFlightsByFlightNumber 根据航班号获取航班信息
func (s *FlightInquiryServer) GetFlightsByFlightNumber(ctx context.Context, in *pb.GetFlightsByFlightNumberReq) (*pb.GetFlightsByFlightNumberResp, error) {
	l := logic.NewGetFlightsByFlightNumberLogic(ctx, s.svcCtx)
	return l.GetFlightsByFlightNumber(in)
}

// QuireTransferFlights 中转航班查询
func (s *FlightInquiryServer) QuireTransferFlights(ctx context.Context, in *pb.QuireTransferFlightsReq) (*pb.QuireTransferFlightsResp, error) {
	l := logic.NewQuireTransferFlightsLogic(ctx, s.svcCtx)
	return l.QuireTransferFlights(in)
}

//  根据指定航班信息提供返程机票推荐(仅支持直飞)
func (s *FlightInquiryServer) RecommendReturnJourneyByFlightInfo(ctx context.Context, in *pb.RecommendReturnJourneyByFlightInfoReq) (*pb.RecommendReturnJourneyByFlightInfoResp, error) {
	l := logic.NewRecommendReturnJourneyByFlightInfoLogic(ctx, s.svcCtx)
	return l.RecommendReturnJourneyByFlightInfo(in)
}
