// Code generated by goctl. DO NOT EDIT!
// Source: flightInquiry.proto

package server

import (
	"context"

	"uranus/app/flightInquiry/cmd/rpc/internal/logic"
	"uranus/app/flightInquiry/cmd/rpc/internal/svc"
	"uranus/app/flightInquiry/cmd/rpc/pb"
)

type FlightInquiryServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFlightInquiryServer
}

func NewFlightInquiryServer(svcCtx *svc.ServiceContext) *FlightInquiryServer {
	return &FlightInquiryServer{
		svcCtx: svcCtx,
	}
}

func (s *FlightInquiryServer) QuireBySetOutTimeAndFlightNumber(ctx context.Context, in *pb.QuireBySetOutTimeAndFlightNumberReq) (*pb.QuireBySetOutTimeAndFlightNumberResp, error) {
	l := logic.NewQuireBySetOutTimeAndFlightNumberLogic(ctx, s.svcCtx)
	return l.QuireBySetOutTimeAndFlightNumber(in)
}

func (s *FlightInquiryServer) QuireBySetOutTimeStartPositionEndPosition(ctx context.Context, in *pb.QuireBySetOutTimeStartPositionEndPositionReq) (*pb.QuireBySetOutTimeStartPositionEndPositionResp, error) {
	l := logic.NewQuireBySetOutTimeStartPositionEndPositionLogic(ctx, s.svcCtx)
	return l.QuireBySetOutTimeStartPositionEndPosition(in)
}
