// Code generated by goctl. DO NOT EDIT.
package types

type FlightReservationReq struct {
	FlightNumber   string `json:"flightNumber"`   // 航班号
	SetOutDate     string `json:"setOutDate"`     // 出发时间
	IsFirstClass   bool   `json:"isFirstClass"`   // 是否是头等舱/商务舱
	DepartPosition string `json:"departPosition"` // 起飞地点
	DepartTime     string `json:"departTime"`     // 起飞时间
	ArrivePosition string `json:"arrivePosition"` // 降落地点
	ArriveTime     string `json:"arriveTime"`     // 降落时间
}

type FlightReservationResp struct {
	OrderSn string `json:"orderSn"` // 订单号
}

type FlightRefundReq struct {
	TicketID uint64 `json:"ticketId"` // 用户要退的票id
}

type FlightRefundResp struct {
	Message string `json:"message"` // 退票成功的提示信息
}

type FlightChangeReq struct {
	TicketID uint64 `json:"ticketId"` // 要改的票id
	SpaceID  uint64 `json:"spaceId"`  // 目标舱位id
}

type FlightChangeResp struct {
	Message string `json:"message"` // 改签成功的提示信息
}
