// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	flightOrder "uranus/app/order/cmd/api/internal/handler/flightOrder"
	"uranus/app/order/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/userFlightOrderList",
				Handler: flightOrder.UserFlightOrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/userFlightOrderDetail",
				Handler: flightOrder.UserFlightOrderDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/flightOrder/v1"),
	)
}
